services:
  postgres:
    image: postgres:15-alpine
    container_name: virtubuild-postgres-dev
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-virtubuild}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-virtubuild123}
      POSTGRES_DB: ${POSTGRES_DB:-virtubuild_db}
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - virtubuild-network-dev
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER:-virtubuild} -d ${POSTGRES_DB:-virtubuild_db}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: virtubuild-pgadmin-dev
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@virtubuild.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin123}
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data_dev:/var/lib/pgadmin
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - virtubuild-network-dev

  virtubuild-api-dev:
    image: node:20-alpine
    container_name: virtubuild-api-dev
    restart: unless-stopped
    working_dir: /app
    ports:
      - "9000:9000"
    environment:
      - NODE_ENV=development
      - APP_DB_HOST=postgres
      - APP_DB_PORT=5432
      - APP_DB_USERNAME=${POSTGRES_USER:-virtubuild}
      - APP_DB_PASSWORD=${POSTGRES_PASSWORD:-virtubuild123}
      - APP_DB_DATABASE=${POSTGRES_DB:-virtubuild_db}
      - PORT=9000
      - APP_SECRET_KEY=${API_KEY:-your-secret-api-key-here}
      - APP_JWT_SECRET_KEY=${JWT_SECRET:-your-jwt-secret-key-here}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN:-24h}
      - CORS_ORIGIN=${CORS_ORIGIN:-http://localhost:4200}
      - LOG_LEVEL=${LOG_LEVEL:-debug}
    volumes:
      - ./virtubuild-api:/app
      - /app/node_modules
    command: >
      sh -c "
        echo '🚀 Installing dependencies...' &&
        npm install &&
        echo '📡 Setting up database...' &&
        npm run db:setup &&
        echo '✅ Database setup completed!' &&
        echo '🎯 Starting development server with live reload...' &&
        npm run dev
      "
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - virtubuild-network-dev

  virtubuild-frontend-dev:
    image: node:20-alpine
    container_name: virtubuild-frontend-dev
    restart: unless-stopped
    working_dir: /app
    ports:
      - "4200:4200"
    environment:
      - NODE_ENV=development
    volumes:
      - ./virtubuildapp:/app
      - /app/node_modules
    command: >
      sh -c "
        echo '🚀 Installing dependencies...' &&
        npm install &&
        echo '🎯 Starting development server with live reload...' &&
        npm start -- --host 0.0.0.0 --port 4200 --poll 2000
      "
    depends_on:
      - virtubuild-api-dev
    networks:
      - virtubuild-network-dev

volumes:
  postgres_data_dev:
    driver: local
  pgadmin_data_dev:
    driver: local

networks:
  virtubuild-network-dev:
    driver: bridge
