services:
  postgres:
    image: postgres:15-alpine
    container_name: virtubuild-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-virtubuild}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-virtubuild123}
      POSTGRES_DB: ${POSTGRES_DB:-virtubuild_db}
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - virtubuild-network
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER:-virtubuild} -d ${POSTGRES_DB:-virtubuild_db}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: virtubuild-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@virtubuild.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin123}
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - virtubuild-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: virtubuild-app
    restart: unless-stopped
    ports:
      - "4200:4200"
      - "9000:9000"
    environment:
      - NODE_ENV=production
      - API_PORT=9000
      - FRONTEND_PORT=4200
    env_file:
      - ./virtubuild-api/.env
      - ./virtubuildapp/.env
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - virtubuild-network
    volumes:
      - ./virtubuild-api:/app/api
      - ./virtubuildapp:/app/frontend
      - /app/api/node_modules
      - /app/frontend/node_modules

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  virtubuild-network:
    driver: bridge
